language: node_js
git:
  depth: 1
before_install:
node_js:
- 10
- 9
# - 8
# - 7
# - 6
# - 5
# - 4
notifications:
  email: false
jobs:
  include:
  - stage: lint
    install: npm install standard
    scirpt: node_modules/.bin/standard
  - stage: coverage
    install: npm install istanbul coveralls
    script: npm run --silent node -- --require ./node_modules/m.test/global.js ./node_modules/istanbul/lib/cli.js cover --print detail test
    after_success: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
    deploy:
      - provider: pages
        local-dir: coverage/lcov-report
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        on:
          branch: master
  # - stage: publish
  #   install: ignore
  #   script: npm pack
  #   after_deploy:
  #   - BEFORE_DEPLOY_VERSION=$(npm view $PWD version)
  #   - git config --local user.name "Travis CI"
  #   - git config --local user.email "travis@travis-ci.org"
  #   - git tag $(npm run --silent node -- --print "process.env.npm_package_version")
  #   - git tag -l
  #   deploy:
  #     - provider: releases
      # api_key: "GITHUB OAUTH TOKEN"
      # file: "FILE TO UPLOAD"
      # skip_cleanup: true
      # provider: npm
      # email: ivo.putzer@gmail.com
      # api_key: $NPM_TOKEN
      # on:
      #   branch: master
  #   after_deploy:
  #   - npm_package_version=$(npm run --silent node -- --print "process.env.npm_package_version")
  #   - git rev-parse -q --verify "refs/tags/$npm_package_version" >/dev/null
  #   # - npm run --silent node -- --print "process.env.npm_package_version"
  #   # -
  # allow_failures:
  # - node_js: 5
  # - node_js: 4
