language: node_js
before_install: npx standard
install: npm install --no-optional
git:
  depth: 1
node_js:
- 10
- 9
# - 8
# - 7
# - 6
# - 5
# - 4
cache:
  directories:
  - node_modules
jobs:
  include:

  - stage: coverage
    install: npm install istanbul coveralls
    script: npm run --silent node -- --require ./node_modules/m.test/global.js ./node_modules/istanbul/lib/cli.js cover --print detail test
    deploy:
    - provider: script
      script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
      on: branch: master
    - provider: pages
      skip-cleanup: true
      github-token: ${GITHUB_TOKEN}
      local-dir: coverage/lcov-report
      on:
        branch: master

  - stage: publish
    install: npm pack
    before_script:
    - git config --local user.name "Travis CI"
    - git config --local user.email "travis@travis-ci.org"
    - git tag $(npm run --silent node -- --print "process.env.npm_package_version")
    script: git tag -l
    # deploy:
      # provider: releases
      # api_key: "GITHUB OAUTH TOKEN"
      # file: "FILE TO UPLOAD"
      # skip_cleanup: true
      # provider: npm
      # email: ivo.putzer@gmail.com
      # api_key: $NPM_TOKEN
      # on:
      #   branch: master
  #   after_deploy:
  #   - npm_package_version=$(npm run --silent node -- --print "process.env.npm_package_version")
  #   - git rev-parse -q --verify "refs/tags/$npm_package_version" >/dev/null
  #   # - npm run --silent node -- --print "process.env.npm_package_version"
  #   # -
  # allow_failures:
  # - node_js: 5
  # - node_js: 4
